PLAYER_BASE_SPEED = 2
PLAYER_BASE_LIFE = 100
PLAYER_BASE_LIFE_REGEN = 0
PLAYER_BASE_DASH_COOLDOWN = 3000
PLAYER_BASE_PICKUP_RANGE = 120
PLAYER_BASE_GOLD_RATE = 1
PLAYER_BASE_EXP_RATE = 1
PLAYER_BASE_DASH_FORCE = 8
PLAYER_BASE_ARMOUR = 25

ATTACK_BASE_COOLDOWN = 500
ATTACK_BASE_PROJECTILE_SPEED = 4
ATTACK_BASE_PROJECTILE_WIDTH = 5
ATTACK_BASE_RANGE = 600
ATTACK_BASE_DAMAGE = 10
ATTACK_BASE_CRITICAL_CHANCE = 5
ATTACK_BASE_CRITICAL_MULTIPLIER = 1.5
ATTACK_BASE_PIERCE_COUNT = 0
